driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 1024

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[ntp::default]
    attributes:
      ntp:
        sync_clock: true
        sync_hw_clock: true
  - name: undo
    run_list:
      - recipe[ntp::undo]
